//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_sede_carrera
    {
        public int id_carrera { get; set; }
        public int id_sede { get; set; }
        public Nullable<bool> acreditado { get; set; }
        public decimal costo_anual { get; set; }
        public Nullable<byte> rel_ingresantes_postulantes { get; set; }
    
        public virtual tb_carreras tb_carreras { get; set; }
        public virtual tb_sedes tb_sedes { get; set; }
    }
}
