//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bd_dondeestudiarEntities : DbContext
    {
        public bd_dondeestudiarEntities()
            : base("name=bd_dondeestudiarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<det_sede_carrera> det_sede_carrera { get; set; }
        public virtual DbSet<tb_areas> tb_areas { get; set; }
        public virtual DbSet<tb_carreras> tb_carreras { get; set; }
        public virtual DbSet<tb_cursos> tb_cursos { get; set; }
        public virtual DbSet<tb_generales> tb_generales { get; set; }
        public virtual DbSet<tb_instituciones> tb_instituciones { get; set; }
        public virtual DbSet<tb_perfil_profesional> tb_perfil_profesional { get; set; }
        public virtual DbSet<tb_roles> tb_roles { get; set; }
        public virtual DbSet<tb_sedes> tb_sedes { get; set; }
        public virtual DbSet<tb_ubigueos> tb_ubigueos { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<sp_ubigeo_Result> sp_ubigeo(string ubicacion)
        {
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ubigeo_Result>("sp_ubigeo", ubicacionParameter);
        }
    }
}
