//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_perfil_profesional
    {
        public int id_carrera { get; set; }
        public int id_perfil { get; set; }
        public string desc_perfil { get; set; }
        public System.DateTime fec_reg { get; set; }
    
        public virtual tb_carreras tb_carreras { get; set; }
    }
}
