//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_sedes()
        {
            this.det_sede_carrera = new HashSet<det_sede_carrera>();
        }
    
        public int id_sede { get; set; }
        public int id_institucion { get; set; }
        public string nom_sede { get; set; }
        public string cod_ubigueo { get; set; }
        public string direccion { get; set; }
        public string telf { get; set; }
        public string coordenada_x { get; set; }
        public string coordenada_y { get; set; }
        public bool estado { get; set; }
        public System.DateTime fec_reg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<det_sede_carrera> det_sede_carrera { get; set; }
        public virtual tb_instituciones tb_instituciones { get; set; }
        public virtual tb_ubigueos tb_ubigueos { get; set; }
    }
}
