//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ubigueos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ubigueos()
        {
            this.tb_sedes = new HashSet<tb_sedes>();
        }
    
        public string cod_ubigueo { get; set; }
        public string cod_dep { get; set; }
        public string desc_dep { get; set; }
        public string cod_prov { get; set; }
        public string desc_prov { get; set; }
        public string cod_dist { get; set; }
        public string desc_dist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sedes> tb_sedes { get; set; }
    }
}
