//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DondeEstudiar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public string dni_user { get; set; }
        public string nom_user { get; set; }
        public string ape_user { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string foto { get; set; }
        public byte id_rol { get; set; }
        public Nullable<bool> estado { get; set; }
        public System.DateTime fec_reg { get; set; }
    
        public virtual tb_roles tb_roles { get; set; }
    }
}
